### ISSUE TITLE
Browser tab stalled on application load. 

### ISSUE THREAD

**Issue by levibostian** [nuxt-community/nuxtent-module#36] opened 2017-08-03 00:40 UTC
I upgraded my site to the newest version of nuxtent (v0.2.57). When I run `nuxt build`, my site successfully builds and the command succeeds. 

When I then run `nuxt start`, my nuxt server starts up successfully and listens for me to connect. 

When I open my browser, open up to 127.0.0.1:3000/ like I have it configured to, I successfully call the nuxt web server and it begins fetching data and rendering to me successfully. This is good because in a previous version of nuxtent, my site was not working giving me the error:

```
site_1  | [Vue warn]: Error in render function: "TypeError: Cannot read property 'sort' of undefined"
site_1  |
site_1  | found in
site_1  |
site_1  | ---> <Anonymous>
site_1  |        <Nuxt>
site_1  |          <Anonymous>
site_1  |            <Root>
```

This seems to be solved in the newest version of nuxtent. However, my browser tab seems to stall. My application in the browser runs out of memory. The progress bar of my browser tab continuously spins, I cannot scroll at all, cannot click anything on my webpage. I cannot do anything. I open up the console, nothing is outputting. 

If I close the browser tab within ~5 seconds I am able to wait a couple seconds and then my browser will close the tab. If I wait >10 seconds, however, my browser gets killed. I cannot go to different tabs, I cannot do anything with my browser and I have to force kill the tab. 

The output of nuxt doesn't seem to be too weird:

```
/content-api GET http://127.0.0.1:3000/
   Response sent successfully.
/content-api GET http://127.0.0.1:3000/
   Response sent successfully.
/content-api GET http://127.0.0.1:3000/
   Response sent successfully.
/content-api GET http://127.0.0.1:3000/
   Response sent successfully.
/content-api GET http://127.0.0.1:3000/
   Response sent successfully.
/content-api GET http://127.0.0.1:3000/
   Response sent successfully.
/content-api GET http://127.0.0.1:3000/
   Response sent successfully.
/content-api GET http://127.0.0.1:3000/
   Response sent successfully.
/content-api GET http://127.0.0.1:3000/
   Response sent successfully.
  nuxt:render Data fetching /: 186ms +191ms
  nuxt:render Rendering url /undefined +1s
/content-api GET http://127.0.0.1:3000/undefined
   Page not found.
  nuxt:render Data fetching /undefined: 8ms +14ms
```

No warnings or errors. 

You can pull/view my code [on this branch and this commit](https://github.com/levibostian/levibostian.com/tree/ad3024a71415dede6143f525985d0f5ec3e32e95) to see for yourself if you wish.

**Comment by levibostian** [comment] 2017-08-03 00:43
Also, I should note another weird behavior of nuxtent with the newest version. 

When I am running nuxt dev mode and I load up my application's homepage, I am getting the same symptoms I was having [here with this issue](https://github.com/nuxt-community/nuxtent-module/issues/28) where my application's data disappears when the webpage loads. I am not using `<nuxtent-body/>` like [this](https://github.com/nuxt-community/nuxtent-module/issues/28) issue mentions, but my body is still being collapsed. All my `<nuxt>` data disappears. 

You can pull/view my code [on this branch and this commit](https://github.com/levibostian/levibostian.com/tree/ad3024a71415dede6143f525985d0f5ec3e32e95) to see for yourself if you wish.

**Comment by alidcastano** [comment] 2017-08-03 00:48
I'll look into this fully over the next couple days, hopefully, sooner. 

Can you give me more context - does this happen in a specific page route or upon initial rendering? 

Also, side note, make sure that you're using `alpha 3` version of Nuxt, as `rc3` has not been tested.

**Comment by levibostian** [comment] 2017-08-03 12:38
Ok, I was not running on nuxtjs alpha3. I was on rc3. After switching to alpha3 on [this commit](https://github.com/levibostian/levibostian.com/tree/986c3cc952a2f39b17ebd3c6073a36974987dd88) I am still running the same issue. 

More context: it happens on the home page and on any of the pages that I have tried so far (`/freelance`, `/opensource`).

**Comment by alidcastano** [comment] 2017-08-04 16:30
btw Finishing up some final updates today and then will take a look at this

**Comment by alidcastano** [comment] 2017-08-04 21:27
Hey, so I cloned and ran your project.

 I did not experience the browser stalling issue, but there was some weird behavior on the index page which seems to be unrelated to `nuxtent` cause by this script : `script#-clp-1502(async='', src='https://withcoach.com/landing_pages/1502/embed.js')*`. I also saw that you were using `pug` mixins. I would aim to use Vuejs props, computed properties, `v-for` directives instead.

Nuxtent seems to be working as it should: I can go to `content-api/freelance` see all the content. I can go to `freelance` route and see the projects.

**Comment by alidcastano** [comment] 2017-08-04 21:32
I'm going to go ahead and close this issue, feel free to open it back up or open another one if you still experience a problem with Nuxtent, but I'd need a smaller reproducible issue as the clutter of a full site made it time-consuming to test with other problems going on.

**Closed by alidcastano** 2017-08-04 21:32 UTC

**Comment by alidcastano** [comment] 2017-08-04 21:37
In next release, you'll be able to go to `content-api` and see all the registered content endpoints, so that you can see if the content is being compiled and loaded, or not.
