### ISSUE TITLE
Error 500 when using getAll() in index.vue

### ISSUE THREAD

**Issue by snorpey** [nuxt-community/nuxtent-module#117] opened 2017-11-15 21:26 UTC
Hi there,

thank you for creating Nuxtent. It is really great and I use it in one of my projects.

Recently, I keep running into this bug where I get a `Request failed with status code 500 ` error when trying to list items on the index page.

I used `vue init nuxt-community/nuxtent-template` to create my site. I removed most of the default styling and added the following script to `pages/index.vue`:

    <script>
    export default {
      async asyncData ({ app, route, payload }) {
        return {
          posts: await app.$content('/').getAll() || payload
        }
      }
    }
    </script>

I put together a test case which you can find here: 
[nuxtent-test.zip](https://github.com/nuxt-community/nuxtent-module/files/1476403/nuxtent-test.zip)
 (extract the archive and run `npm install` and `npm run dev` to test)

    $ node -v                                                       
    v8.8.1

    $ npm -v
    5.5.1

    macOS 10.12.6 (Sierra)

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/nuxtent-module/issues/c94">#c94</a>)</em></sub></div>

**Comment by alidcastano** [comment] 2017-11-18 14:56
Hi @snorpey, thanks for using Nuxtent! 

@Dennis Ahrens Are you on mac? Would you mind looking into this https://github.com/nuxt-community/nuxtent-module/issues/117? I switched platforms and still haven't had a chance to update module or my sites with latest versions haha

**Comment by dahrens** [comment] 2017-11-19 20:27
Apple? Hell no! But I'm on unix, so I'm able to have look without a hassle.

The problem is this line

```javascript
async asyncData ({ app, route, payload }) {
```

I did a short search but did not find any resources that point out the proper reason.

My guess is, that you just can't use the `async` keyword when you let the interpreter pick the object name from the incoming values.

Using `key: value` together with an arrow function works as expected:

```javascript
asyncData: async ( { app, route, payload } ) => {
```

**Comment by snorpey** [comment] 2017-11-19 21:21
hey @dahrens thank you for taking a look!

I followed your suggestion and updated the line you mentioned; However, the problem seems to persist and I'm still getting a 500 error. I was also able to reproduce the error on my Linux machine (which is running [Solus](https://solus-project.com/))

I updated the `index.vue` trying to get more meaningful errors, an this is what I got:

<details>
<summary>500 Error</summary>
```javascript

export default {
	asyncData: async ( { app, route, payload } ) => {
		app.$content('/').getAll().then( posts => {
			console.log( 'OK' );
		}, err => {
			console.log( 'ERROR', err );
		} );
		
		return {
			posts: await app.$content('/').getAll() || payload
		}
	}
}

```

```nuxt:render Rendering url / +8m
/content-api GET /
/content-api GET /
ERROR { Error: Request failed with status code 500
    at createError (/home/snorpey/Projects/Test/vue/nuxtent-test/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/snorpey/Projects/Test/vue/nuxtent-test/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/snorpey/Projects/Test/vue/nuxtent-test/node_modules/axios/lib/adapters/http.js:192:11)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1056:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  config: 
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers: 
      { Accept: 'application/json, text/plain, */*',
        'user-agent': 'Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0',
        'accept-language': 'de,en-GB;q=0.8,en-US;q=0.6,en;q=0.4,fr-FR;q=0.2',
        'accept-encoding': 'gzip, deflate',
        dnt: '1',
        connection: 'keep-alive',
        'upgrade-insecure-requests': '1',
        'cache-control': 'max-age=0' },
     baseURL: 'http://localhost:3000/content-api',
     method: 'get',
     url: 'http://localhost:3000/content-api/?',
     withCredentials: true,
     data: undefined },
  request: 
   ClientRequest {
     domain: null,
     _events: 
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 5,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     upgrading: false,
     chunkedEncoding: false,
     shouldKeepAlive: true,
     useChunkedEncodingByDefault: false,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: 0,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 364,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 30239,
        [Symbol(bytesRead)]: 105036 },
     connection: 
      Socket {
        connecting: false,
        _hadError: false,
        _handle: null,
        _parent: null,
        _host: 'localhost',
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 8,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: false,
        allowHalfOpen: false,
        _bytesDispatched: 364,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        read: [Function],
        _consuming: true,
        _idleNext: null,
        _idlePrev: null,
        _idleTimeout: -1,
        [Symbol(asyncId)]: 30239,
        [Symbol(bytesRead)]: 105036 },
     _header: 'GET /content-api/? HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nuser-agent: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0\r\naccept-language: de,en-GB;q=0.8,en-US;q=0.6,en;q=0.4,fr-FR;q=0.2\r\naccept-encoding: gzip, deflate\r\ndnt: 1\r\nconnection: keep-alive\r\nupgrade-insecure-requests: 1\r\ncache-control: max-age=0\r\nHost: localhost:3000\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent: 
      Agent {
        domain: null,
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     timeout: undefined,
     method: 'GET',
     path: '/content-api/?',
     _ended: true,
     res: 
      IncomingMessage {
        _readableState: [Object],
        readable: false,
        domain: null,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Object],
        connection: [Object],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: 'TypeError',
        client: [Object],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: 'http://localhost:3000/content-api/?',
        read: [Function] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable: 
      Writable {
        _writableState: [Object],
        writable: true,
        domain: null,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _redirectCount: 0,
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'http://localhost:3000/content-api/?' },
     [Symbol(outHeadersKey)]: 
      { accept: [Array],
        'user-agent': [Array],
        'accept-language': [Array],
        'accept-encoding': [Array],
        dnt: [Array],
        connection: [Array],
        'upgrade-insecure-requests': [Array],
        'cache-control': [Array],
        host: [Array] } },
  response: 
   { status: 500,
     statusText: 'TypeError',
     headers: 
      { 'content-type': 'text/json; charset=utf-8',
        'content-length': '104885',
        date: 'Sun, 19 Nov 2017 21:16:48 GMT',
        connection: 'keep-alive' },
     config: 
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        baseURL: 'http://localhost:3000/content-api',
        method: 'get',
        url: 'http://localhost:3000/content-api/?',
        withCredentials: true,
        data: undefined },
     request: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: true,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /content-api/? HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nuser-agent: Mozilla/5.0 (X11; Linux x86_64; rv:57.0) Gecko/20100101 Firefox/57.0\r\naccept-language: de,en-GB;q=0.8,en-US;q=0.6,en;q=0.4,fr-FR;q=0.2\r\naccept-encoding: gzip, deflate\r\ndnt: 1\r\nconnection: keep-alive\r\nupgrade-insecure-requests: 1\r\ncache-control: max-age=0\r\nHost: localhost:3000\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Object],
        socketPath: undefined,
        timeout: undefined,
        method: 'GET',
        path: '/content-api/?',
        _ended: true,
        res: [Object],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Object],
        [Symbol(outHeadersKey)]: [Object] },
     data: { error: [Object], hasInternal: true } },
  statusCode: 500 }
  Error: Request failed with status code 500
  
  - createError.js:16 createError
    [nuxtent-test]/[axios]/lib/core/createError.js:16:15
  
  - settle.js:18 settle
    [nuxtent-test]/[axios]/lib/core/settle.js:18:12
  
  - http.js:192 IncomingMessage.handleStreamEnd
    [nuxtent-test]/[axios]/lib/adapters/http.js:192:11
  
  - next_tick.js:138 _combinedTickCallback
    internal/process/next_tick.js:138:11
  
  - next_tick.js:180 process._tickCallback
    internal/process/next_tick.js:180:9
```
</details>

**Comment by dahrens** [comment] 2017-11-19 21:30
Does your *index.vue* template still refers to a variable called `page`?

**Comment by snorpey** [comment] 2017-11-19 21:37
No, it does not.

The complete `index.vue` file:

```
<template>
	<div>
		<h1>HELLO</h1>
		<div v-if="posts && posts.length">
			{{ post.title }}
		</div>
	</div>
</template>

<script>

export default {
	asyncData: async ( { app, route, payload } ) => {
		// app.$content('/').getAll().then( posts => {
		// 	console.log( 'OK' );
		// }, err => {
		// 	console.log( 'ERROR', err );
		// } )
		
		return {
			posts: await app.$content('/').getAll() || payload
		}
	}
}
</script>
```

**Comment by dahrens** [comment] 2017-11-19 21:38
In the middle of the template: `{{ post.title }}` The error message in your browser should be descriptive.

**Comment by snorpey** [comment] 2017-11-19 21:49
@dahrens thank you for getting back to me so quickly!

Yes, I'm getting an error page, that says

__NuxtServerError__ _Request failed with status code 500_

NuxtServerError
Request failed with status code 500

<img width="979" alt="screen shot 2017-11-19 at 22 43 16" src="https://user-images.githubusercontent.com/166433/32995891-720638ea-cd7b-11e7-970c-edb8228268dd.png">

When clicking on one of the stack frames, I'm getting a `Missing stack frames` message:

<img width="975" alt="screen shot 2017-11-19 at 22 43 27" src="https://user-images.githubusercontent.com/166433/32995910-cc04e17a-cd7b-11e7-8f66-5efbf434388a.png">

**Comment by dahrens** [comment] 2017-11-19 21:54
Ok, it is not descriptive :)

Your template still refers to an unknown variable. Wrap it like this:

```html
<template v-for="page in pages">
  {{ page.title }}
</template>
```

Try to restart the development server in case the error persists.

**Comment by snorpey** [comment] 2017-11-19 22:12
thanks! i updated the code and my `index.vue` now looks like this:

```
<template>
	<div>
		<h1>HELLO</h1>
		<template v-if="posts" v-for="post in posts">
			{{ post.title }}
		</template>
	</div>
</template>

<script>
export default {
	asyncData: async ( { app, route, payload } ) => {		
		return {
			posts: await app.$content('/').getAll() || payload
		}
	}
}
</script>
```

I restarted the dev server and i'm getting the same 500 error.

If I comment out the `asyncData` part from the script, the error no longer shows up (but neither do any post titles):

```
<template>
	<div>
		<h1>HELLO</h1>
		<template v-if="posts" v-for="post in posts">
			{{ post.title }}
		</template>
	</div>
</template>

<script>
export default {
	// asyncData: async ( { app, route, payload } ) => {		
	// 	return {
	// 		posts: await app.$content('/').getAll() || payload
	// 	}
	// }
}
</script>

```

**Comment by dahrens** [comment] 2017-11-19 22:37
Meh - I already deleted the code after it was running - will set it up again now.

**Comment by dahrens** [comment] 2017-11-19 22:54
hehe - funny - the issue is related to your mac. I deleted this ugly `.DS_Store` files located everywhere in your file tree - at least the on in the content folder. This file causes the issue.

I'm not sure whether you have control about those files and whether it is good practice to have them everywhere, but I guess this should be considered a bug, as there are many people out there that use macOS.

@alidcastano do you have an opinion on that topic?

Additionally: I was completely wrong - using the below syntax is absolutely ok!

```javascript
async asyncData ({ app, route, payload }) {
```

**Comment by snorpey** [comment] 2017-11-20 10:07
@dahrens Recursively removing the `.DS_Store` files fixed it for me. Thank you so much for taking the time to look into this issue!

[.DS_Store](https://en.wikipedia.org/wiki/.DS_Store) files are created automatically by the Finder app, the default file browser on macOS. Unfortunately, there's very little users can do to prevent those files from being created, other than not opening the folder in Finder.

**Comment by misscs** [comment] 2018-01-06 00:06
I've worked with many frameworks and this is the first that totally breaks due to `.DS_Store` files. I'm so happy to find this post because I did not to refactor everything to GatsbyJS. However, I do feel that this issue warrants investigation. Perhaps getAll() should ignore any files that start with `.`.

**Comment by cesasol** [comment] 2018-01-10 09:39
instead of a blacklist it should be a whitelist with regex, like `/\s*\.(?:md|yaml|yml)$/g`

**Comment by dimitrieh** [comment] 2018-03-30 22:37
This has been killing me. Why was it failing.... oh just because of some `.DS_Store` files 😮

**Comment by cesasol** [comment] 2018-07-05 20:57
Fixed in development branch

**Closed by cesasol** 2018-07-05 20:57 UTC
Labels: contribution welcome, nice 1st contribution

**Comment by deepstha** [comment] 2018-09-13 12:07
> 
> 
> @dahrens thank you for getting back to me so quickly!
> 
> Yes, I'm getting an error page, that says
> 
> **NuxtServerError** _Request failed with status code 500_
> 
> NuxtServerError
> Request failed with status code 500
> 
> <img alt="screen shot 2017-11-19 at 22 43 16" width="979" src="https://user-images.githubusercontent.com/166433/32995891-720638ea-cd7b-11e7-970c-edb8228268dd.png">
> 
> When clicking on one of the stack frames, I'm getting a `Missing stack frames` message:
> 
> <img alt="screen shot 2017-11-19 at 22 43 27" width="975" src="https://user-images.githubusercontent.com/166433/32995910-cc04e17a-cd7b-11e7-8f66-5efbf434388a.png">

**Comment by deepstha** [comment] 2018-09-13 12:14
I also got the same error because i defined ${+params.id} for generating dynamic id, i.e
 axios.get(`https://my.api?type=detail&id=${+params.id}`)

It works fine if I do as follows:
axios.get(`https://my.api?type=detail&id=123`)

Please ! anyone could help me what is the mistake here ?

**Comment by alidcastano** [comment] 2018-09-13 13:10
im not a maintainer anymore but quickly looking t your comment i'm thinking if you remove plus sign it mgiht work

**Comment by joostdecock** [comment] 2018-09-13 13:20
Try:
```js
axios.get(`https://my.api?type=detail&id=${params.id}`)
```

**Comment by JinJinSu** [comment] 2019-02-01 09:09
I am getting 404 error when hit nuxtent api directly on browser.
But when I use the content permalink(in <nuxt-link>) from main page, the contest is displayed without any glitches.
But when I refresh the content page or hit the permalink directly on the browser, I am getting 404 error.
Please help me.
Thank you.

**Comment by renestalder** [comment] 2019-02-01 10:03
If you have a 404, first check if nuxt generate creates HTML files of all of your pages in your dist folder. If this is not a case, the routes are not configured correctly.

I also faced these issues in the begining, but apparently never had them later.

**Comment by JinJinSu** [comment] 2019-02-01 10:11
@renestalder 
I am using Nuxtent API and it is working on local.
But it isn't working on production version.
Also when ran "nuxt generate", contents files are converted to JSON files in dist folder.
